import { useEffect, useRef, useState } from "react";
import axios from "axios";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { Capacitor } from "@capacitor/core";
import { Directory, Filesystem } from "@capacitor/filesystem";
import { Share } from "@capacitor/share";
import studentService from "../services/studentService";

const PREDICTION_API="https://ai-career-backend-vj8d.onrender.com/api/predictions";
const COURSE_API="https://ai-career-backend-vj8d.onrender.com/api/courses";

function CareerReport(){
 const [student,setStudent]=useState(null),[prediction,setPrediction]=useState(null),[courses,setCourses]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[pdfLoading,setPdfLoading]=useState(false);
 const reportRef=useRef(null);
 const getField=(o,...keys)=>{if(!o)return "-";for(const k of keys){if(o[k]!==undefined&&o[k]!==null&&String(o[k]).trim()!=="")return o[k];}return "-";};
 const getConfidence=v=>{let n=Number(v);if(!Number.isFinite(n))return 0;if(n>0&&n<=1)n*=100;return Math.round(n*100)/100;};
 useEffect(()=>{(async()=>{try{setLoading(true);setError("");const uid=localStorage.getItem("userId");if(!uid)throw new Error("User ID not found. Please login again.");const st=await studentService.getByUserId(uid);if(!st?.id)throw new Error("Student profile not found.");setStudent(st);
   let local=null;try{const x=localStorage.getItem("latestPrediction");if(x)local=JSON.parse(x);}catch{}
   const r=await axios.get(`${PREDICTION_API}/student/${st.id}`);let arr=Array.isArray(r.data)?r.data:(r.data?[r.data]:[]);
   const latest=arr.length?[...arr].sort((a,b)=>{const d=(b.createdAt?new Date(b.createdAt).getTime():0)-(a.createdAt?new Date(a.createdAt).getTime():0);return d||Number(b.id||0)-Number(a.id||0);})[0]:null;
   const finalP=latest||local;if(!finalP)throw new Error("Please generate the AI career prediction first.");const c=getField(finalP,"recommendedCareer","career","predictedCareer");if(c==="-")throw new Error("Career information is missing from the prediction.");setPrediction(finalP);localStorage.setItem("latestPredictedCareer",String(c).trim());localStorage.setItem("recommendedCareer",String(c).trim());
   const cr=await axios.get(`${COURSE_API}/career/${encodeURIComponent(String(c).trim())}`);setCourses(Array.isArray(cr.data)?cr.data:[]);
 }catch(e){console.error("CAREER REPORT ERROR:",e);setError(e.response?.data?.message||e.response?.data?.error||e.message||"The career report is not loading.");}finally{setLoading(false);}})();},[]);
 const handleDownloadPDF=async()=>{if(!reportRef.current||pdfLoading)return;try{setPdfLoading(true);if(document.fonts?.ready)await document.fonts.ready;await new Promise(r=>setTimeout(r,250));const canvas=await html2canvas(reportRef.current,{scale:Math.min(2,window.devicePixelRatio||1.5),useCORS:true,allowTaint:false,backgroundColor:"#fff",logging:false,scrollX:0,scrollY:-window.scrollY,windowWidth:reportRef.current.scrollWidth,windowHeight:reportRef.current.scrollHeight});const pdf=new jsPDF({orientation:"portrait",unit:"mm",format:"a4",compress:true});const pw=210,ph=297,m=8,w=pw-m*2,h=canvas.height*w/canvas.width;const img=canvas.toDataURL("image/jpeg",.92);let offset=0;pdf.addImage(img,"JPEG",m,m,w,h,undefined,"FAST");offset=ph-m*2;while(offset<h){pdf.addPage();pdf.addImage(img,"JPEG",m,m-offset,w,h,undefined,"FAST");offset+=ph-m*2;}const career=String(getField(prediction,"recommendedCareer","career","predictedCareer")).replace(/[^a-z0-9]+/gi,"_").replace(/^_+|_+$/g,"").slice(0,60)||"Career";const name=`Career_Report_${career}.pdf`;
   if(Capacitor.isNativePlatform()){const uri=pdf.output("datauristring"),base64=uri.split(",")[1];if(!base64)throw new Error("PDF data could not be created.");await Filesystem.writeFile({path:name,data:base64,directory:Directory.Documents,recursive:true});const fileUri=await Filesystem.getUri({directory:Directory.Documents,path:name});try{await Share.share({title:"Career Report PDF",text:"Your CareerAI career report",url:fileUri.uri,dialogTitle:"Save or share Career Report"});}catch(e){console.log("Share sheet closed",e);}}else pdf.save(name);
 }catch(e){console.error("PDF GENERATION ERROR:",e);alert(e?.message||"PDF could not be generated. Please try again.");}finally{setPdfLoading(false);}};
 if(loading)return <div className="page-container"><div className="form-card"><h2>📊 Career Report Loading...</h2><p>Latest predictions and courses are loading...</p></div></div>;
 if(error)return <div className="page-container"><div className="error-message">{error}</div></div>;
 const career=getField(prediction,"recommendedCareer","career","predictedCareer"),confidence=getConfidence(getField(prediction,"confidence")),studentName=getField(student,"name","studentName","fullName"),email=getField(student,"email"),studentId=getField(student,"id","studentId"),tenth=getField(student,"tenthMarks","marks10","tenth"),twelfth=getField(student,"twelfthMarks","marks12","twelfth"),grad=getField(student,"graduationMarks","graduationPercentage","graduation"),semester=getField(student,"semester","currentSemester"),backlogs=getField(student,"backlogs","backlog");
 return <div className="page-container"><div className="page-header no-print"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:"20px",flexWrap:"wrap"}}><div><h1>📊 Career Report</h1><p>A comprehensive report based on your profile, skills, academics, and predictions.</p></div><button type="button" className="main-button" onClick={handleDownloadPDF} disabled={pdfLoading} style={{padding:"14px 25px",fontSize:"16px",whiteSpace:"nowrap"}}>{pdfLoading?"⏳ Creating PDF...":"🖨️ Download PDF"}</button></div></div>
 <div ref={reportRef}>
  <div className="form-card"><h2>👤 Student Details</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:"25px",marginTop:"20px"}}><div><strong>Name</strong><p>{studentName}</p></div><div><strong>Email</strong><p>{email}</p></div><div><strong>Student ID</strong><p>{studentId}</p></div></div></div>
  <div className="form-card"><h2>🎓 Academic Details</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:"16px",marginTop:"20px"}}><div className="profile-completion-card"><strong>10th Marks</strong><h3>{tenth}</h3></div><div className="profile-completion-card"><strong>12th Marks</strong><h3>{twelfth}</h3></div><div className="profile-completion-card"><strong>Graduation Marks</strong><h3>{grad}</h3></div><div className="profile-completion-card"><strong>Semester</strong><h3>{semester}</h3></div><div className="profile-completion-card"><strong>Backlogs</strong><h3>{backlogs}</h3></div></div></div>
  <div className="profile-completion-card" style={{marginBottom:"25px",padding:"30px"}}><div><p style={{margin:0,fontSize:"16px"}}>🤖 AI Recommended Career</p><h1 style={{marginTop:"10px",marginBottom:"10px"}}>🎯 {career}</h1><p style={{margin:0}}>Career recommendation generated using AI/ML model based on profile, academic performance, skills and assessment score.</p></div><div className="completion-circle"><span>{confidence}%</span></div></div>
  {prediction?.reason&&<div className="form-card" style={{marginBottom:"25px"}}><h2>💡 Why this career?</h2><p>{prediction.reason}</p></div>}
  <div className="form-card"><h2>📚 Recommended Courses</h2><p>These courses are aligned with your AI-recommended career, <strong>{career}</strong></p>{courses.length===0?<p>No recommended courses are available for this career.</p>:<div style={{display:"grid",gap:"20px",marginTop:"25px"}}>{courses.map((course,i)=><div key={course.id||i} style={{padding:"25px",borderRadius:"16px",border:"1px solid #e5e7eb",background:"#f8f9ff"}}><h3 style={{marginTop:0}}>📖 {getField(course,"name","courseName","title")}</h3><p><strong>Platform:</strong> {getField(course,"platform")}</p><p><strong>Duration:</strong> {getField(course,"duration")}</p>{course.url&&<a href={course.url} target="_blank" rel="noopener noreferrer" className="main-button no-print" style={{display:"block",width:"100%",marginTop:"15px",textAlign:"center",textDecoration:"none",boxSizing:"border-box"}}>View Course ↗</a>}</div>)}</div>}</div>
 </div></div>;
}
export default CareerReport;
