# =========================================================
# DATABASE - AIVEN MYSQL
# =========================================================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# =========================================================
# SERVER
# =========================================================

server.port=${PORT:8080}
server.address=0.0.0.0


# =========================================================
# PYTHON ML SERVICE
# =========================================================

ml.service.url=${ML_SERVICE_URL:http://localhost:5000/predict}


# =========================================================
# EMAIL - GMAIL SMTP
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.required=true